Deprovision requests should only include quicknode-id, as documented in guides
quiknode-labs/qn-marketplace-cli pull request #17
Opened 2024-10-01 18:50 UTC by luccastera

2024-10-01 19:13 UTC, abunsen requested changes

2024-10-01 19:13 UTC, abunsen commented on cmd/deprovision.go
> -			DeprovisionAt: time.Now().Unix(),
think we should keep this.

2024-10-01 19:13 UTC, abunsen commented on cmd/pudd.go
> -			DeprovisionAt: time.Now().Unix(),
same

2024-10-01 19:13 UTC, abunsen commented on marketplace/provisioning.go
> -	DeprovisionAt int64  `json:"deprovision-at"`
same

2024-11-07 09:02 UTC, 0xsergen approved these changes

2024-11-07 15:00 UTC, merged